Add flavor support

diff --git a/tazlito b/tazlito
--- a/tazlito
+++ b/tazlito
@@ -59,7 +59,7 @@ ROOTCD=$DISTRO/rootcd
 usage ()
 {
 	echo -e "\nSliTaz Live Tool - Version: $VERSION\n
-\033[1mUsage: \033[0m `basename $0` [command] [list|iso] [dir]
+\033[1mUsage: \033[0m `basename $0` [command] [list|iso|flavor] [dir]
 \033[1mCommands: \033[0m\n
   usage           Print this short usage.
   stats           View Tazlito and distro configuration statistics.
@@ -67,6 +67,10 @@ usage ()
   configure       Configure the main config file or a specific tazlito.conf.
   gen-iso         Generate a new ISO from a distro tree.
   gen-initiso     Generate a new initramfs and ISO from the distro tree.
+  list-flavors    List all available package lists on the mirror.
+  gen-flavor      Generate a new live-CD description.
+  show-flavor     Show live-CD description.
+  get-flavor      Get a flavor's list of packages.
   extract-distro  Extract and ISO to a directory and rebuild LiveCD tree.
   gen-distro      Generated a Live distro and ISO from a list of packages.
   clean-distro    Remove all files generated by gen-distro.
@@ -96,6 +100,11 @@ yesorno()
 	N|n) answer="n";;
 	*) read answer;;
 	esac
+}
+
+field()
+{
+	grep "^$1" "$2" | sed 's/.*: \([0-9KMG\.]*\).*/\1/'
 }
 
 todomsg()
@@ -226,12 +235,8 @@ gen_initramfs()
 	mv $INITRAMFS $ROOTCD/boot
 }
 
-# Print ISO and rootfs size.
-distro_stats()
+distro_sizes()
 {
-	echo ""
-	echo -e "\033[1mDistro statistics\033[0m"
-	echo "================================================================================"
 	echo "Build date      : `date +%Y%m%d\ \at\ \%H:%M:%S`"
 	echo "Packages        : `ls -1 $ROOTFS$INSTALLED | wc -l`"
 	echo "Rootfs size     : `du -sh $ROOTFS`"
@@ -239,6 +244,15 @@ distro_stats()
 	echo "ISO image size  : `du -sh $ISO_NAME.iso`"
 	echo "================================================================================"
 	echo ""
+}
+
+# Print ISO and rootfs size.
+distro_stats()
+{
+	echo ""
+	echo -e "\033[1mDistro statistics\033[0m"
+	echo "================================================================================"
+	distro_sizes
 }
 
 # Creat an empty configuration file.
@@ -435,6 +449,103 @@ Distro directory    : $DISTRO"
 		echo "Rootcd size     : `du -sh rootcd`"
 		echo "================================================================================"
 		echo ""
+		;;
+	list-flavors)
+		# Show available flavors.
+		if [ ! -s /etc/tazlito/flavors.list -o "$2" == "--recharge" ]; then
+			download flavors.list -O - > /etc/tazlito/flavors.list
+		fi
+		cat /etc/tazlito/flavors.list
+		;;
+	show-flavor)
+		# Show flavor description.
+		FLAVOR=$2
+		if [ ! -f "$FLAVOR.flavor" ]; then
+			echo "File $FLAVOR.flavor not found."
+			exit 1
+		fi
+		mkdir $TMP_DIR
+		zcat $FLAVOR.flavor | ( cd $TMP_DIR; cpio -i 2> /dev/null )
+		if [ "$3" = "--brief" ]; then
+			if [ "$4" != "--noheader" ]; then
+				echo "Name            Sizes        Description"
+				echo "================================================================================"
+			fi
+			printf "%-15.15s %5.5s/%5.5s %-51s\n" "$FLAVOR" \
+				"$(field ISO $TMP_DIR/$FLAVOR.desc)" \
+				"$(field Rootfs $TMP_DIR/$FLAVOR.desc)" \
+				"$(grep ^Description $TMP_DIR/$FLAVOR.desc | cut -d: -f2)"
+		else
+			echo "================================================================================"
+			cat $TMP_DIR/$FLAVOR.desc
+		fi
+		rm -Rf $TMP_DIR
+		;;
+	gen-flavor)
+		# Generate a new flavor form then last iso image generation.
+		FLAVOR=$2
+		if [ -z "$FLAVOR" ]; then
+			echo -n "Flavor name : "
+			read FLAVOR
+			[ -z "$FLAVOR" ] && exit 1
+		fi
+		check_rootfs
+		FILES="$FLAVOR.pkglist"
+		echo -n "Creating file $FLAVOR.flavor..."
+		for i in rootcd rootfs; do
+			if [ -d "$ADDFILES/$i" ] ; then
+				FILES="$FILES\n$FLAVOR.$i"
+				( cd "$ADDFILES/$i"; find . | \
+				  cpio -o -H newc 2> /dev/null | gzip -9 ) > $FLAVOR.$i
+			fi
+		done
+		answer=`grep -s ^Description $FLAVOR.desc`
+		answer=${answer#Description     : }
+		if [ -z "$answer" ]; then
+			echo -en "\nDescription : "
+			read answer
+		fi
+		echo "Flavor          : $FLAVOR" > $FLAVOR.desc
+		echo "Description     : $answer" >> $FLAVOR.desc
+		( cd $DISTRO; distro_sizes) >> $FLAVOR.desc
+		\rm -f $FLAVOR.pkglist 2> /dev/null
+		for i in $(ls $ROOTFS$INSTALLED); do
+			eval $(grep ^VERSION= $ROOTFS$INSTALLED/$i/receipt)
+			echo "$i-$VERSION" >> $FLAVOR.pkglist
+		done
+		echo -e "$FLAVOR.desc\n$FILES" | cpio -o -H newc 2>/dev/null | \
+			gzip -9 > $FLAVOR.flavor
+		rm `echo -e $FILES`
+		status
+		;;
+	get-flavor)
+		# Get a flavor's files and prepare for gen-distro.
+		FLAVOR=$2
+		if [ -f $FLAVOR.flavor ] || download $FLAVOR.flavor; then
+			echo -n "Cleaning $DISTRO..."
+			rm -R $DISTRO 2> /dev/null
+			mkdir -p $DISTRO
+			status
+			mkdir $TMP_DIR
+			zcat $FLAVOR.flavor | ( cd $TMP_DIR; cpio -i 2>/dev/null )
+			echo -n "Create distro-packages.list..."
+			mv $TMP_DIR/$FLAVOR.pkglist distro-packages.list
+			status
+			for i in rootcd rootfs; do
+				if [ -f $TMP_DIR/$FLAVOR.$i ]; then
+					mkdir -p "$ADDFILES/$i"
+					zcat $TMP_DIR/$FLAVOR.$i | \
+						( cd "$ADDFILES/$i"; cpio -id 2> /dev/null)
+				fi
+			done
+			echo -n "Update tazlito.conf..."
+			[ -f tazlito.conf ] || cp /etc/tazlito/tazlito.conf .
+			cat tazlito.conf | grep -v "^#VOLUM_NAME" | \
+			sed "s/^VOLUM_NA/VOLUM_NAME=\"SliTaz $FLAVOR\"\\n#VOLUM_NA/" \
+				> tazlito.conf.$$ && mv tazlito.conf.$$ tazlito.conf
+			status
+			rm -Rf $TMP_DIR
+		fi
 		;;
 	gen-distro)
 		# Generate a live distro tree with a set of packages.
