Add command writiso (use current fs as it) and tmp fix lzma dictionary size

diff --git a/tazlito b/tazlito
--- a/tazlito
+++ b/tazlito
@@ -71,7 +71,7 @@ FLAVORS_REPOSITORY=/home/slitaz/flavors
 usage ()
 {
 	echo -e "\nSliTaz Live Tool - Version: $VERSION\n
-\033[1mUsage: \033[0m `basename $0` [command] [list|iso|flavor] [dir]
+\033[1mUsage: \033[0m `basename $0` [command] [list|iso|flavor|compression] [dir|iso]
 \033[1mCommands: \033[0m\n
   usage           Print this short usage.
   stats           View Tazlito and distro configuration statistics.
@@ -92,6 +92,7 @@ usage ()
   gen-distro      Generate a Live distro and ISO from a list of packages.
   clean-distro    Remove all files generated by gen-distro.
   check-distro    Help to check if distro is ready to release.
+  writeiso        Use running system to generate a bootable ISO (with /home).
   merge           Merge multiple rootfs into one iso.
   repack          Recompress rootfs into iso with maximum ratio.
   emu-iso         Emulate an ISO image with Qemu.
@@ -283,15 +284,20 @@ gen_livecd_isolinux()
 
 lzma_history_bits()
 {
-	local n
-	local sz
-	n=20	# 1Mb
-	sz=$(du -sk $1 | cut -f1)
-	while [ $sz -gt 1024 -a $n -lt 28 ]; do
-		n=$(( $n + 1 ))
-		sz=$(( $sz / 2 ))
-	done
-	echo $n
+	#
+	# This genertae ISO who boot with Qemu but give
+	# rootfs errors in frugal or liveUSB mode.
+	#
+	#local n
+	#local sz
+	#n=20	# 1Mb
+	#sz=$(du -sk $1 | cut -f1)
+	#while [ $sz -gt 1024 -a $n -lt 28 ]; do
+		#n=$(( $n + 1 ))
+		#sz=$(( $sz / 2 ))
+	#done
+	#echo $n
+	echo 24
 }
 
 lzma_switches()
@@ -1459,6 +1465,135 @@ EOT
 		echo "================================================================================"
 		echo ""
 		;;
+	writeiso)
+		# Writefs to ISO image including /home unlike gen-distro we dont use
+		# packages to generate a rootfs, we build a compressed rootfs with all 
+		# current filesystem similar to 'tazusb writefs'.
+		#
+		DISTRO="/home/slitaz/distro"
+		ROOTCD="$DISTRO/rootcd"
+		if [ -z $2 ]; then
+			COMPRESSION=none
+		else
+			COMPRESSION=$2
+		fi
+		if [ -z $3 ]; then
+			ISO_NAME="slitaz"
+		else
+			ISO_NAME="$3"
+		fi
+		check_root
+		# Start info
+		echo ""
+		echo -e "\033[1mWrite filesystem to ISO\033[0m
+===============================================================================
+The command writeiso will write all the current filesystem into a suitable cpio 
+archive (rootfs.gz) and generate a bootable ISO image (slitaz.iso). 
+
+Archive compression: $COMPRESSION"
+		echo ""
+		
+		# Save some space
+		rm /var/cache/tazpkg/* -r -f
+		rm -rf /home/slitaz/distro
+
+		# Optionally remove sound card selection
+		echo -n "Do you wish to remove the sound card selection (No/yes/exit) ? "
+		read anser
+		case $anser in
+			e|E|"exit"|Exit)
+				exit 0 ;;
+			y|Y|yes|Yes)
+				echo -n "Removing current sound card selection..."
+				rm -f /var/lib/sound-card-driver
+				rm -f /etc/asound.state ;;
+			*)
+				echo -n "Keeping current sound card selection..." ;;
+		esac
+		status
+		
+		# Optionally remove screen resolution
+		echo -n "Do you wish to remove the screen resolution (No/yes/exit) ? "
+		read anser
+		case $anser in
+			e|E|"exit"|Exit)
+				exit 0 ;;
+			y|Y|yes|Yes)
+				echo -n "Removing current screen resolution..."
+				rm -f /etc/X11/screen.conf 
+				rm -f /etc/X11/xorg.conf ;;
+			*)
+				echo -n "Keeping current screen resolution..." ;;
+		esac
+		status
+		
+		# Create list of files including default user files since it is defined in /etc/passwd
+		# and some new users might have been added.
+		find /bin /etc /init /sbin /var /dev /lib /root /usr /home >/tmp/list
+
+		for dir in /proc /sys /tmp /mnt /media /media/cdrom /media/flash /media/usbdisk
+		do
+			echo $dir >>/tmp/list
+		done
+
+		# Generate initramfs with specified compression
+		if [ "$COMPRESSION" = "lzma" ]; then
+			echo -n "Creating rootfs.gz with lzma compression... "
+			cat /tmp/list | cpio -o -H newc | lzma e -si -so > /rootfs.gz
+
+		elif [ "$COMPRESSION" = "gzip" ]; then
+			echo -n "Creating rootfs.gz with gzip compression... "
+			cat /tmp/list | cpio -o -H newc | gzip -9 > /rootfs.gz
+
+		else
+			echo -n "Creating rootfs.gz without compression... "
+			cat /tmp/list | cpio -o -H newc > /rootfs.gz
+		fi
+		status
+
+		# Move freshly generated rootfs to the cdrom.
+		mkdir -p $ROOTCD/boot
+		mv /rootfs.gz $ROOTCD/boot
+		
+		# Now we need the kernel and isolinux files.
+		if mount /dev/cdrom /media/cdrom 2>/dev/null; then
+			cp /media/cdrom/boot/bzImage $ROOTCD/boot
+			cp -a /media/cdrom/boot/isolinux $ROOTCD/boot
+			umount /media/cdrom
+		else
+			echo -e "\nUnable to mount the cdrom to copy the Kernel and needed files.\n"
+			exit 1
+		fi
+		
+		# Generate the iso image.
+		cd $DISTRO
+		echo "Generating ISO image..."
+		genisoimage -R -o $ISO_NAME.iso -b boot/isolinux/isolinux.bin \
+		-c boot/isolinux/boot.cat -no-emul-boot -boot-load-size 4 \
+		-V "SliTaz" -input-charset iso8859-1 -boot-info-table $ROOTCD
+		if [ -x /usr/bin/isohybrid ]; then
+			echo -n "Create hybrid ISO..."
+			/usr/bin/isohybrid $ISO_NAME.iso 2> /dev/null
+			status
+		fi
+		echo -n "Creating the ISO md5sum..."
+		md5sum $ISO_NAME.iso > $ISO_NAME.md5
+		status
+
+		echo "==============================================================================="
+		echo "ISO image: `du -sh /home/slitaz/distro/$ISO_NAME.iso`"
+		echo ""
+		echo -n "Exit or burn ISO to cdrom (Exit|burn)? "; read anser
+		case $anser in
+			burn)
+				eject
+				echo -n "Please insert a blank cdrom and press ENTER..."
+				read i && sleep 2
+				tazlito burn-iso /home/slitaz/distro/$ISO_NAME.iso
+				echo -en "----\nENTER to continue..."; read i ;;
+			*)
+				exit 0 ;;
+		esac ;;
 	burn-iso)
 		# Guess cdrom device, ask user and burn the ISO.
 		#
